### ISSUE TITLE
Payments service missing in consul service mesh tutorial

### ISSUE THREAD

**Issue by ChanderG** [hashicorp/learn-consul-kubernetes#64]
When following the tutorial here https://learn.hashicorp.com/tutorials/consul/service-mesh-deploy, cannot fully interact with the `hashicups` app. 

Though the tutorial itself does not cover the app functionality, trying to run through payment on the demo app leads to following error:
```
Error: GraphQL error: Post http://localhost:18000: dial tcp [::1]:18000: connect: connection refused
```

I see the app version here https://github.com/hashicorp/hashicups-setups/tree/main/local-k8s-consul-deployment/k8s has more services - specifically the payments service which seems to be missing in this repo's `service-mesh/deploy/hashicups` folder.

**Comment by krastin** [comment]
Good spot! 
Commit 3f8bce0f1f2f513a3f3dfa239676bc41bcd895ee fixes this, thank you for reporting!
