### ISSUE TITLE
Consul k8s tutorial broken ─ missing value for -consul-api-timeout

### ISSUE THREAD

**Issue by carpioldc** [hashicorp/learn-consul-kubernetes#69]
Following [Getting Started with Consul Service Mesh for Kubernetes], I encountered an issue.

### Environment

K8s versions
```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.22.11+IKS
```

Helm version
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

### Steps performed

Following the tutorial, I downloaded the git repo and configured the helm repo. I installed the helm chart afterwards:

```
git clone https://github.com/hashicorp/learn-consul-kubernetes.git
cd learn-consul-kubernetes/service-mesh/deploy
helm repo add hashicorp https://helm.releases.hashicorp.com
helm repo update
helm install -f config.yaml consul hashicorp/consul --create-namespace -n consul --version "0.43.0"
```
### Expected

All pods in the consul namespace running and healthy.

### Got

Pods of `consul-controller` and `consul-connect-injector` deployments are in CrashLoopBackOff. The logs of both components show:

```
-consul-api-timeout must be set to a value greater than 0
```

[Getting Started with Consul Service Mesh for Kubernetes]: https://learn.hashicorp.com/tutorials/consul/service-mesh-deploy

**Comment by carpioldc** [comment]
Patching both deployments to add the missing argument makes the pods run successfully.

**Comment by krastin** [comment]
Hi @carpioldc!
The guide has been updated and the `helm install` line no longer calls for version `0.43.0` - higher versions have this bug fixed as reported in the [Changelog here](https://github.com/hashicorp/consul-k8s/blob/main/CHANGELOG.md#0440-may-17-2022). Thank you for taking the time to report this issue.
